### ISSUE TITLE
Nothing happens! 

### ISSUE THREAD

**Issue by NesooseN** [nextcloud/user_retention#122]
We are using latest version of NC v18.0.3, with users that are not active over 1 year, and app is not deleting them at all. Is there anything to try ?

**Comment by nickvergessen** [comment]
The app "discovers" the users and also takes that into account, to not delete users immediately that never logged in.
But maybe since we have the config option now:
https://github.com/nextcloud/user_retention#users-who-did-not-log-in

That should be taken into account for that case and ignore the discovery day
